// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"github/lyr1cs/v0/oj-exam-backend/app/api/internal/svc"
	"github/lyr1cs/v0/oj-exam-backend/common/httpm"

	"github.com/zeromicro/go-zero/rest"
	"github.com/zeromicro/go-zero/rest/httpx"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	httpx.SetOkHandler(httpm.Succeedhandler)
	server.AddRoutes(
		[]rest.Route{
			{
				// 检查学生信息
				Method:  http.MethodPost,
				Path:    "/check",
				Handler: CheckHandler(serverCtx),
			},
			{
				// 开始考试
				Method:  http.MethodPost,
				Path:    "/exam",
				Handler: ExamHandler(serverCtx),
			},
		},
	)
}
